# Generated by Django 3.1.7 on 2021-04-17 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('item_name', models.TextField(max_length=264)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.TextField(max_length=64)),
                ('price', models.IntegerField(null=True)),
                ('note', models.TextField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Item_relate_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_app.item')),
            ],
        ),
    ]
