# Generated by Django 3.1.7 on 2021-04-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_auto_20210417_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_relate_company',
            old_name='item_id',
            new_name='item_name',
        ),
    ]
