# Generated by Django 3.1.7 on 2021-04-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_auto_20210417_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_relate_Company',
        ),
    ]
